### ISSUE TITLE
Can you share the converted YT-BB data, i.e. youtubebbdevkit2017?

### ISSUE THREAD

**Issue by yiminglin-ai** [leeyeehoo/SiamVGG#9]
Hi,
Thank you open-sourcing your work. I have been converting the YT-BB dataset using the script  https://github.com/mbuckler/youtube-bb/blob/master/voc_convert.py but it takes forever. Do you think you can share the converted folder youtubebbdevkit2017 via google drive? 
Many thanks,
Yiming

**Comment by leeyeehoo** [comment]
You can explore that in the ./dataset folder
